FROM python:3.12

COPY ./ ./

RUN python -m pip install --upgrade pip && pip install -r requirements.txt

RUN pip install fastapi[all]

RUN pip install uvicorn[standard]

EXPOSE 80

CMD ["uvicorn", "inference_api:app", "--reload", "--host", "0.0.0.0", "--port", "80"]

